repositories:
  - name: bedag
    url: https://bedag.github.io/helm-charts

helmDefaults:
  wait: true
  timeout: 600
  createNamespace: true
  atomic: true

releases:
  - name: postgres
    namespace: postgres
    chart: oci://ghcr.io/cloudpirates-io/helm-charts/postgres
    version: 0.18.3
    values:
      - ../shared_values/postgres.yaml

  - name: envoy-gateway
    namespace: gateway
    chart: oci://docker.io/envoyproxy/gateway-helm
    version: v1.7.1
    values:
      - ../shared_values/envoy-gateway.yaml

  - name: gateway
    namespace: default
    chart: bedag/raw
    version: 2.0.2
    needs:
      - gateway/envoy-gateway
    disableValidationOnInstall: true
    disableOpenAPIValidation: true
    values:
      - ../shared_values/gateway-raw.yaml